language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - if $TRAVIS_JDK_VERSION == "openjdk8" then export IMAGE_NAME=openjdk:8u232-jre-stretch
  - if $TRAVIS_JDK_VERSION == "openjdk11" then export IMAGE_NAME=openjdk:11-jre-stretch

install: true

script:
  - echo $TRAVIS_JDK_VERSION
  - echo $IMAGE_NAME

after_success:
  - bash <(curl -s https://codecov.io/bash)
