language: java
sudo: false # faster builds

jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - echo $TRAVIS_JDK_VERSION
  - env
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk8" ]; then echo "java8"; fi
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then  echo "java11"; fi

install: true

script:
  - echo TRAVIS_JDK_VERSION is  $TRAVIS_JDK_VERSION
  - echo IMAGE_NAME is $IMAGE_NAME
  - env

after_success:
  - bash <(curl -s https://codecov.io/bash)
