language: java
sudo: false # faster builds

jdk:
  - openjdk11
    - env IMAGE_NAME=openjdk:11-jre-stretch
  - openjdk8
    - env IMAGE_NAME=openjdk:8u232-jre-stretch
cache:
  directories:
    - $HOME/.m2

install: true

script:
  - if [ "$TRAVIS_BRANCH" == "develop" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then
     echo $IMAGE_NAME;
    else
     echo $IMAGE_NAME;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
